#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/guest/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# Is supposed to set clipboard but it aint working
clipmgr=$(type -p parcellite)
[ -x "$clipmgr" ] && "$clipmgr" &

#Sets resolution to appropriate fields
#xrandr -s 1920x1080

#Sets wallpaper
fbsetbg -f ~/.fluxbox/backgrounds/wallpaper.jpg

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/guest/.fluxbox/log"
